version: '3.5'

services:

  helloworld:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:mysecretpassword@helloworld-db/helloworld
    command: sh -c 'alembic upgrade head && uvicorn --host 0.0.0.0 --port 8000 --reload helloworld.app:app'
#    command: sh -c 'uvicorn --host 0.0.0.0 --port 8000 --reload helloworld.app:app'
#    healthcheck:
#      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/8000'
#      interval: 5s
#      timeout: 5s
#      retries: 12
#    volumes:
#      - ./helloworld:/app/helloworld/helloworld
    depends_on:
      - helloworld-db
    ports:
      - "8000:8000"

  helloworld-db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: helloworld
      PGDATA: /data/postgres
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/5432'
      interval: 5s
      timeout: 5s
      retries: 12
    volumes:
       - helloworld_db:/data/postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  helloworld_db:
  pgadmin:
