"""add_size

Revision ID: f329ba7e55d2
Revises: 714acf457b32
Create Date: 2023-03-21 20:18:15.169803

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f329ba7e55d2'
down_revision = '714acf457b32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('size', sa.Integer(), nullable=True))
    op.execute("UPDATE file SET size = 0")
    op.alter_column('file', 'size', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'size')
    # ### end Alembic commands ###
